INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (1,'Miłosz','Miły',1996,'niezły ziomek',3);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (2,'Adam','Adamowski',1994,'dobry typ',1);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (3,'Kuba','Lamusowski',1990,'tego nie lubię',2);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (4,'Michał','Kochański',1992,'idiota, zaczął tydzień temu robić projekt',4);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (5,'Karol','Kowalski',1988,NULL,3);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (6,'Krzysztof','Serce',1991,NULL,4);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (7,'Daniel','Wysypka',1990,NULL,4);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (8,'Aleksander','Oczko',1989,NULL,3);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (9,'Patrycja','Niedźwiedź',1987,NULL,2);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (10,'Aleksandra','Lornetka',1986,NULL,1);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (11,'Hubert','Mokry',1960,NULL,1);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (12,'Gerard','Rączka',1997,'jak w takim wieku on się tu dostał!?',4);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (13,'Paweł','Dziecko',1969,'co taki staruch robi na studiach?',2);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (14,'Patryk','Młody',1993,NULL,2);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (15,'Pelagia','Kozecka',1994,NULL,4);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (16,'Jakub','Rodny',1991,NULL,4);
INSERT INTO `students` (`idStudent`,`firstName`,`lastName`,`yearOfBorn`,`about`,`idGroup`) VALUES (17,'Wacław','Rączka',1992,NULL,3);

INSERT INTO `groups` (`idGroup`,`name`,`about`,`idStarosty`) VALUES (1,'Pracowicy','muszę wziąć od nich numery - pewnie zrobimy biznes',2);
INSERT INTO `groups` (`idGroup`,`name`,`about`,`idStarosty`) VALUES (2,'Mądrzy','dobrze się uczą, ale w ogóle nie pogadasz',3);
INSERT INTO `groups` (`idGroup`,`name`,`about`,`idStarosty`) VALUES (3,'Głupi','pogadasz, ale idioci',1);
INSERT INTO `groups` (`idGroup`,`name`,`about`,`idStarosty`) VALUES (4,'Leserzy','tępię ich jak mogę, ale co zrobisz - im nie zależy',4);